sudo: required
services:
  - docker

before_install:
  - docker build -t veldmpet/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true veldmpet/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-149260610097"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id:
    secure: "$AWS_SECRET_KEY"